version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb_image
    restart: always
    expose:
      - "3306"
    networks:
      - 42-network-database
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MARIADB_USER_PASSWORD"]
      retries: 10
      interval: 5s
      start_interval: 5s
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PASSWORD=${MARIADB_USER_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress_image
    restart: always
    expose:
      - "9000"
    networks:
      - 42-network-database
      - 42-network-services
    volumes:
      - wordpress:/var/www/wordpress
    environment:
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy

  adminer:
    container_name: adminer
    build:
      context: ./bonus/adminer
    image: adminer_image
    restart: always
    expose:
      - "9000"
    networks:
      - 42-network-database
      - 42-network-services
    volumes:
      - adminer:/var/www/adminer
    depends_on:
      mariadb:
        condition: service_healthy

  redis:
    container_name: redis
    build:
      context: ./bonus/redis
    image: redis_image
    restart: always
    expose:
      - "6379"
    networks:
      - 42-network-services

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx_image
    restart: always
    ports:
      - 443:443
      - 8080:8080
    networks:
      - 42-network-services
    volumes:
      - wordpress:/var/www/wordpress
      - adminer:/var/www/adminer
    environment:
      - CERTS_=${CERTS_}
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
      - adminer
      - redis

networks:
  42-network-services:
  42-network-database:

volumes:
  mariadb:
    name: "mariadb"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/gpanico/data/mariadb"
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/gpanico/data/wordpress"
  adminer:
    name: "adminer"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/gpanico/data/adminer"
