version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: gpanico/mariadb
    restart: always
    expose:
      - "3306"
    networks:
      - 42-network-database
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MARIADB_USER_PASSWORD"]
      retries: 10
      interval: 5s
      start_interval: 5s
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PASSWORD=${MARIADB_USER_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: gpanico/wordpress
    restart: always
    expose:
      - "9000"
    networks:
      - 42-network-database
      - 42-network-services
    volumes:
      - wordpress:/var/www/wordpress
    environment:
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy

  adminer:
    container_name: adminer
    build:
      context: ./requirements/adminer
    image: gpanico/adminer
    restart: always
    expose:
      - "9000"
    networks:
      - 42-network-database
      - 42-network-services
    volumes:
      - adminer:/var/www/adminer
    depends_on:
      mariadb:
        condition: service_healthy

  redis:
    container_name: redis
    build:
      context: ./requirements/redis
    image: gpanico/redis
    restart: always
    expose:
      - "6379"
    networks:
      - 42-network-services

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: gpanico/nginx
    restart: always
    ports:
      - "443:443"
      - "8080:8080"
    networks:
      - 42-network-services
    volumes:
      - wordpress:/var/www/wordpress
      - adminer:/var/www/adminer
    environment:
      - CERTS_=${CERTS_}
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
      - adminer
      - redis

  ftp:
    container_name: ftp
    build:
      context: ./requirements/ftp
    image: gpanico/ftp
    restart: always
    ports:
      - "2020:20"
      - "2021:21"
      - "5000-6000:5000-6000"
    networks:
      - 42-network-ftp
    volumes:
      - wordpress:/var/www/wordpress
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
    depends_on:
      - wordpress


networks:
  42-network-services:
  42-network-database:
  42-network-ftp:

volumes:
  mariadb:
    name: "mariadb"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/gpanico/data/mariadb"
  wordpress:
    name: "wordpress"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/gpanico/data/wordpress"
  adminer:
    name: "adminer"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/gpanico/data/adminer"
